name: Java CI

on: [push]

env:
  CC_TEST_REPORTER_ID: 0510b89c96f9d82cd22890e8ef71cb34a73dc95bdb896447070fd2c8ef86a95d
  JACOCO_SOURCE_PATH: 'mathml-converters mathml-core mathml-gold mathml-libs mathml-similarity mathml-utils'

jobs:
  CI Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '6'
          cache: 'npm'
      - name: Install LaTeXML, LibrSVG2-dev, Codeclimate Reporter
        run: |
          sudo apt-get install -y latexml librsvg2-dev
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
      - name: Start Mathoid Server
        run: |
          npm i git+https://git@github.com/physikerwelt/mathoid-server.git
          cd node_modules/mathoid
          sudo chmod +x server.js
          ./server.js -c ../../.github/config.dev.yaml &
          cd ../..
      - name: Maven Install
        run: |
          mvn clean -q
          mvn --settings .travis/settings.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
      - name: Maven Test
        run: mvn clean test jacoco:report
      - name: Report Test Coverage
        run: |
          source .github/fix-jacoco.sh
          ./cc-test-reporter format-coverage ./target/jacoco-report/jacoco-fix.xml --input-type jacoco > jacoco.log 2>&1
          ./cc-test-reporter upload-coverage -d > jacocoUpload.log 2>&1